### PR TITLE
Change CMD ["help"] to ["--help"]

### PR DESCRIPTION
**Pull request by alajpie**
```
$ sd run -it --rm euantorano/zig
Unrecognized command: help
See `/usr/local/bin/zig/zig --help` for detailed usage information
$ sd run -it --rm euantorano/zig --help
Usage: /usr/local/bin/zig/zig [command] [options]

Commands:
  build                        build project from build.zig
  ...
```

### CODE REVIEW

**Comment by euantorano** [comment]
Ah, this must have changed at some point. Good catch!

**Comment by alajpie** [comment]
It looks like the build failed for some (I presume) unrelated reason. Could you try to run it again?

**Comment by euantorano** [comment]
Yeah, I think it’s related the the Python side of things, it’s happened before and has been fixed by increments by version numbers. I’ll try fix it this afternoon, thanks for the heads up!

**Comment by euantorano** [comment]
All fixed, sorry about that!

**Pull request merged**
